// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChIHakSgvbXABnnjXqJ6NJoIuQvTe5xyU',
    appId: '1:283388415379:web:2d3d29ace131e3fb7fac66',
    messagingSenderId: '283388415379',
    projectId: 'to-do-app-11bd7',
    authDomain: 'to-do-app-11bd7.firebaseapp.com',
    storageBucket: 'to-do-app-11bd7.firebasestorage.app',
    measurementId: 'G-TB291E7PH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDajIosuV1mY0yOUqSdDvLO4KfremiHnYc',
    appId: '1:283388415379:android:638e8b394b2737337fac66',
    messagingSenderId: '283388415379',
    projectId: 'to-do-app-11bd7',
    storageBucket: 'to-do-app-11bd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzi-es-upPg7IhKsYMyYcZWS42t2QXNg',
    appId: '1:283388415379:ios:3b3896e4f93e44ed7fac66',
    messagingSenderId: '283388415379',
    projectId: 'to-do-app-11bd7',
    storageBucket: 'to-do-app-11bd7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXzi-es-upPg7IhKsYMyYcZWS42t2QXNg',
    appId: '1:283388415379:ios:3b3896e4f93e44ed7fac66',
    messagingSenderId: '283388415379',
    projectId: 'to-do-app-11bd7',
    storageBucket: 'to-do-app-11bd7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChIHakSgvbXABnnjXqJ6NJoIuQvTe5xyU',
    appId: '1:283388415379:web:5d159560fe0ebca77fac66',
    messagingSenderId: '283388415379',
    projectId: 'to-do-app-11bd7',
    authDomain: 'to-do-app-11bd7.firebaseapp.com',
    storageBucket: 'to-do-app-11bd7.firebasestorage.app',
    measurementId: 'G-GP521HVG4R',
  );
}
